/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f6eefc",
        "primary-fixed-dim": "#d2bbff",
        "on-secondary-container": "#fffbff",
        "outline-variant": "#ccc3d8",
        "error": "#ba1a1a",
        "secondary-fixed": "#ffdad7",
        "surface-container-highest": "#e8dfee",
        "on-primary-fixed-variant": "#5a00c6",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#d2bbff",
        "surface-bright": "#fef7ff",
        "error-container": "#ffdad6",
        "primary-container": "#7c3aed",
        "tertiary": "#704500",
        "primary": "#630ed4",
        "secondary": "#b71422",
        "surface": "#fef7ff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-surface-variant": "#4a4455",
        "surface-dim": "#dfd7e6",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary-container": "#ffe1c0",
        "background": "#fef7ff",
        "on-secondary-fixed": "#410004",
        "surface-variant": "#e8dfee",
        "secondary-fixed-dim": "#ffb3ae",
        "surface-container-low": "#f9f1ff",
        "on-surface": "#1d1a24",
        "on-background": "#1d1a24",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#25005a",
        "on-secondary": "#ffffff",
        "surface-tint": "#732ee4",
        "on-secondary-fixed-variant": "#930014",
        "on-primary": "#ffffff",
        "outline": "#7b7487",
        "primary-fixed": "#eaddff",
        "on-tertiary-fixed": "#2a1700",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary-container": "#905b00",
        "secondary-container": "#db3237",
        "surface-container": "#f3ebfa",
        "inverse-surface": "#332f39",
        "surface-container-high": "#ede5f4",
        "on-primary-container": "#ede0ff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xl": "32px",
        "md": "16px",
        "lg": "24px",
        "sm": "8px",
        "unit": "4px",
        "margin-mobile": "20px",
        "xs": "4px",
        "margin-desktop": "40px",
        "gutter": "16px"
      },
      "fontFamily": {
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"]
      },
      "fontSize": {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "500" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "34px", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
